### ISSUE TITLE
Client should have more method like http endpoints

### ISSUE THREAD

**Issue by TanNgocDo** [mappum/js-tendermint#17]
We should add some endpoints like :"tx_search" to method.js

I see branch tendermint v-0.23 has updated with more method on method.js. But should we update on npm package too ?

**Comment by mappum** [comment]
Agreed, probably makes sense to add methods for the following:
- Tx broadcasting
- Tx queries
- Tx subscriptions

The 0.23.0 update will be published on npm once tendermint 0.23.0 is actually released.

**Comment by mappum** [comment]
I believe now all the methods are up-to-date.
