### ISSUE TITLE
Please update npm package

### ISSUE THREAD

**Issue by ethanfrey** [mappum/js-tendermint#7]
I used `yarn add tendermint` to get the latest (2.0.5) version of js-tendermint off of npm. However, it doesn't support promises, which was odd.

```
   TypeError: "listener" argument must be a function
      
      at Client.once (events.js:341:11)
      at Client.callWs (node_modules/tendermint/lib/client.js:106:14)
      at Client.(anonymous function) [as status] (node_modules/tendermint/lib/client.js:131:19)
      at Client.status (src/client.js:12:32)
```

Looking at the code inside of `node_modules`, I see:

```
  }, {
    key: 'callWs',
    value: function callWs(method, args, cb) {
      var id = Math.random().toString(36);
      var params = convertArgs(args);
      if (method === 'subscribe') {
        this.on(id + '#event', cb);

        // errors won't have "#event"
        this.once(id, function (err) {
          return err ? cb(err) : null;
        });
      } else {
        this.once(id, cb);
      }
      this.ws.write({ jsonrpc: '2.0', id: id, method: method, params: params });
    }
```

However, the same code in github is already super-sized with promises:

https://github.com/mappum/js-tendermint/blob/master/src/rpc.js#L70-L98

I think you just need to rebuild lib and push again to npm. This would be a great help.

**Comment by mappum** [comment]
I have been publishing the new, unstable versions of this package under the incompatible semver version `3.x.x`, with installs still defaulting to `2.x.x` since the new light client hasn't yet been audited for production use. You can install 3 now to get the light client and new Promise API by doing `yarn add tendermint@3`.

BTW, there is one other change, the RPC module is now exported differently:
```js
let { RpcClient } = require('tendermint')

let rpc = RpcClient('ws://localhost:46657')
let status = await rpc.status()
...
```

**Comment by mappum** [comment]
>Can you add this to the README? For the people who love to live on the edge.
>I'd love to audit light client, but it would be good to see a simple test case as well.

Good ideas, I'll update the README and add a light client example.

> AFAIK, supercop uses a different format for secret keys than go/ed25519, maybe also public keys, so I was wondering about compatibility.

That's right, private keys use a different format, but pubkeys and signatures are compatible.
